name: Build and Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create zip package
        run: |
          mkdir -p dist
          zip -r dist/lightwork-wp-plugin.zip . -x '*.git*' -x '*.github*' -x 'dist/*'

      - name: Publish GitHub release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "dist/lightwork-wp-plugin.zip"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true
